# Generated by Django 5.2.8 on 2026-01-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0016_alter_contractorcategory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseInfoProxy",
            fields=[],
            options={
                "verbose_name": "общая информация",
                "verbose_name_plural": "общая информация",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("main.baseinfo",),
        ),
        migrations.CreateModel(
            name="ContractorCategoryProxy",
            fields=[],
            options={
                "verbose_name": "контрагент (сервис)",
                "verbose_name_plural": "контрагенты (сервис)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("main.contractorcategory",),
        ),
        migrations.CreateModel(
            name="ContractorProxy",
            fields=[],
            options={
                "verbose_name": "контрагент",
                "verbose_name_plural": "контрагенты",
                "ordering": ["-category__name", "city", "street", "name"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("main.contractor",),
        ),
        migrations.CreateModel(
            name="OrgStandartProxy",
            fields=[],
            options={
                "verbose_name": "товар (СТО)",
                "verbose_name_plural": "товары (СТО)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("main.orgstandart",),
        ),
        migrations.CreateModel(
            name="ProductCategoryProxy",
            fields=[],
            options={
                "verbose_name": "товар (категория)",
                "verbose_name_plural": "товары (категория)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("main.productcategory",),
        ),
        migrations.CreateModel(
            name="ProductOrgStandartProxy",
            fields=[],
            options={
                "verbose_name": "стандарт организации (СТО)",
                "verbose_name_plural": "стандарты организации (СТО)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("main.productorgstandart",),
        ),
        migrations.CreateModel(
            name="ProductProxy",
            fields=[],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
                "ordering": ["-category__name", "name"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("main.product",),
        ),
    ]
