# Generated by Django 5.2.8 on 2026-03-16 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("main", "0017_ingredient_productingredient_product_ingredients_m2m_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductIngredientProxy",
            fields=[],
            options={
                "verbose_name": "ингредиент товара",
                "verbose_name_plural": "ингредиенты товаров",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("main.productingredient",),
        ),
    ]
