# Generated by Django 5.2.8 on 2026-03-16 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_productingredientproxy"),
    ]

    operations = [
    ]
