# Generated by Django 5.2.8 on 2026-03-16 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_productcategoryworkshopproxy_workshopproxy"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductCategoryWorkshopProxy",
        ),
        migrations.DeleteModel(
            name="WorkshopProxy",
        ),
    ]
