# Generated by Django 5.2.8 on 2026-03-17 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_delete_productcategoryworkshopproxy_and_more"),
        ("main", "0024_productbestbefore"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductBestBeforeProxy",
            fields=[],
            options={
                "verbose_name": "срок годности товара",
                "verbose_name_plural": "сроки годности товара",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("main.productbestbefore",),
        ),
    ]
