# Generated by Django 5.2.8 on 2025-11-17 08:54

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractorCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Название")),
            ],
            options={
                "verbose_name": "контрагент",
                "verbose_name_plural": "контрагенты",
            },
        ),
        migrations.CreateModel(
            name="OrgStandart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Пример:", max_length=256, verbose_name="Название"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Пример:", max_length=64, verbose_name="Код"
                    ),
                ),
            ],
            options={
                "verbose_name": "стандарт организации (СТО)",
                "verbose_name_plural": "стандарты организации (СТО)",
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Название")),
            ],
            options={
                "verbose_name": "категория товара",
                "verbose_name_plural": "категории товаров",
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=512, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "width",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Ширина",
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Ширина",
                    ),
                ),
                ("elements", models.JSONField()),
            ],
            options={
                "verbose_name": "шаблон",
                "verbose_name_plural": "шаблоны",
            },
        ),
        migrations.CreateModel(
            name="Contractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Пример: ООО «Рога и Копыта»",
                        max_length=128,
                        null=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="Тюмень", max_length=128, verbose_name="Город"
                    ),
                ),
                ("street", models.TextField(max_length=256, verbose_name="Улица")),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        help_text="Пример: Взрослая травматология",
                        max_length=128,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Пример: Самокат",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contractor",
                        to="main.contractorcategory",
                        verbose_name="Контрагент",
                    ),
                ),
            ],
            options={
                "verbose_name": "этикетка контрагента",
                "verbose_name_plural": "этикетки контрагентов",
                "ordering": ["-category__name", "city", "street", "name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalContractor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Пример: ООО «Рога и Копыта»",
                        max_length=128,
                        null=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="Тюмень", max_length=128, verbose_name="Город"
                    ),
                ),
                ("street", models.TextField(max_length=256, verbose_name="Улица")),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        help_text="Пример: Взрослая травматология",
                        max_length=128,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Пример: Самокат",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="main.contractorcategory",
                        verbose_name="Контрагент",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical этикетка контрагента",
                "verbose_name_plural": "historical этикетки контрагентов",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOrgStandart",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Пример:", max_length=256, verbose_name="Название"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Пример:", max_length=64, verbose_name="Код"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical стандарт организации (СТО)",
                "verbose_name_plural": "historical стандарты организации (СТО)",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTemplate",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=512, verbose_name="Название"
                    ),
                ),
                (
                    "width",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Ширина",
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Ширина",
                    ),
                ),
                ("elements", models.JSONField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical шаблон",
                "verbose_name_plural": "historical шаблоны",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=82, verbose_name="Название")),
                (
                    "ingredients",
                    models.TextField(max_length=1600, verbose_name="Состав"),
                ),
                (
                    "weight",
                    models.CharField(
                        help_text="Пример: 100/130 гр.",
                        max_length=100,
                        verbose_name="Вес",
                    ),
                ),
                (
                    "best_before",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Количество дней",
                        verbose_name="Срок хранения",
                    ),
                ),
                (
                    "calories",
                    models.DecimalField(
                        decimal_places=1, max_digits=6, verbose_name="Калории"
                    ),
                ),
                (
                    "protein",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="Белки"
                    ),
                ),
                (
                    "fat",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="Жиры"
                    ),
                ),
                (
                    "carbs",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="Углеводы"
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Штрихкод должен содержать ровно 13 цифр",
                                regex="^\\d{13}$",
                            )
                        ],
                        verbose_name="Штрихкод",
                    ),
                ),
                (
                    "caption",
                    models.TextField(
                        default="Хранить при температуре от 0 до +6°С. Продукция может содержать аллергены.",
                        verbose_name="Дополнительная информация",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product",
                        to="main.productcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
                "ordering": ["-category__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalProduct",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField(max_length=82, verbose_name="Название")),
                (
                    "ingredients",
                    models.TextField(max_length=1600, verbose_name="Состав"),
                ),
                (
                    "weight",
                    models.CharField(
                        help_text="Пример: 100/130 гр.",
                        max_length=100,
                        verbose_name="Вес",
                    ),
                ),
                (
                    "best_before",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Количество дней",
                        verbose_name="Срок хранения",
                    ),
                ),
                (
                    "calories",
                    models.DecimalField(
                        decimal_places=1, max_digits=6, verbose_name="Калории"
                    ),
                ),
                (
                    "protein",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="Белки"
                    ),
                ),
                (
                    "fat",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="Жиры"
                    ),
                ),
                (
                    "carbs",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="Углеводы"
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Штрихкод должен содержать ровно 13 цифр",
                                regex="^\\d{13}$",
                            )
                        ],
                        verbose_name="Штрихкод",
                    ),
                ),
                (
                    "caption",
                    models.TextField(
                        default="Хранить при температуре от 0 до +6°С. Продукция может содержать аллергены.",
                        verbose_name="Дополнительная информация",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="main.productcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical товар",
                "verbose_name_plural": "historical товары",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ProductOrgStandart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "org_standart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="org_standart",
                        to="main.orgstandart",
                        verbose_name="Стандарт Организации (СТО)",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="org_standart",
                        to="main.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "стандарт организации (СТО)",
                "verbose_name_plural": "стандарты организации (СТО)",
            },
        ),
    ]
