# Generated by Django 5.2.8 on 2025-11-17 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="template",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="main.template",
                verbose_name="Шаблон",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="template",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product",
                to="main.template",
                verbose_name="Шаблон",
            ),
            preserve_default=False,
        ),
    ]
