# Generated by Django 5.2.8 on 2025-11-22 16:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_historicalproduct_template_product_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512, verbose_name="Название")),
                (
                    "address",
                    models.TextField(
                        help_text="Для этикеток товаров",
                        max_length=512,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "short_address",
                    models.TextField(
                        help_text="Для этикеток контрагентов",
                        max_length=512,
                        verbose_name="Короткий адрес",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=32, verbose_name="Номер телефона"),
                ),
            ],
            options={
                "verbose_name": "общая информация",
                "verbose_name_plural": "общая информация",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalproduct",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical этикетка товара",
                "verbose_name_plural": "historical этикетки товаров",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-category__name", "name"],
                "verbose_name": "этикетка товара",
                "verbose_name_plural": "этикетки товаров",
            },
        ),
        migrations.AddField(
            model_name="contractor",
            name="template",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contractor",
                to="main.template",
                verbose_name="Шаблон",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcontractor",
            name="template",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="main.template",
                verbose_name="Шаблон",
            ),
        ),
        migrations.AlterField(
            model_name="historicalorgstandart",
            name="code",
            field=models.CharField(
                help_text="Пример: 71743495-001-2024", max_length=64, verbose_name="Код"
            ),
        ),
        migrations.AlterField(
            model_name="historicalorgstandart",
            name="name",
            field=models.CharField(
                help_text="Пример: Обеденные блюда готовые, охлажденные из мяса птицы с гарнирами и без",
                max_length=256,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltemplate",
            name="height",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Высота",
            ),
        ),
        migrations.AlterField(
            model_name="orgstandart",
            name="code",
            field=models.CharField(
                help_text="Пример: 71743495-001-2024", max_length=64, verbose_name="Код"
            ),
        ),
        migrations.AlterField(
            model_name="orgstandart",
            name="name",
            field=models.CharField(
                help_text="Пример: Обеденные блюда готовые, охлажденные из мяса птицы с гарнирами и без",
                max_length=256,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="height",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Высота",
            ),
        ),
    ]
