# Generated by Django 5.2.8 on 2025-12-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_baseinfo_alter_historicalproduct_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltemplate",
            name="elements",
            field=models.JSONField(verbose_name="Разметка"),
        ),
        migrations.AlterField(
            model_name="template",
            name="elements",
            field=models.JSONField(verbose_name="Разметка"),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("template", "barcode"), name="unique_barcode_per_template"
            ),
        ),
    ]
