# Generated by Django 5.2.8 on 2025-12-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_historicalbaseinfo_historicalcontractorcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduct",
            name="calories",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Калории"
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="carbs",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Углеводы"
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="fat",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Жиры"
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="protein",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Белки"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="calories",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Калории"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="carbs",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Углеводы"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="fat",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Жиры"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="protein",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Белки"
            ),
        ),
    ]
