# Generated by Django 5.2.8 on 2025-12-11 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_historicalproduct_calories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productorgstandart",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_standart",
                to="main.product",
                verbose_name="Товар",
            ),
        ),
    ]
