# Generated by Django 5.2.8 on 2025-12-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_productorgstandart_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseinfo",
            name="site_url",
            field=models.URLField(
                blank=True,
                help_text="вместе с http:// или https://",
                max_length=512,
                null=True,
                verbose_name="Адрес сайта",
            ),
        ),
        migrations.AddField(
            model_name="historicalbaseinfo",
            name="site_url",
            field=models.URLField(
                blank=True,
                help_text="вместе с http:// или https://",
                max_length=512,
                null=True,
                verbose_name="Адрес сайта",
            ),
        ),
        migrations.AlterField(
            model_name="baseinfo",
            name="address",
            field=models.TextField(
                blank=True,
                help_text="Для этикеток товаров",
                max_length=512,
                null=True,
                verbose_name="Адрес",
            ),
        ),
        migrations.AlterField(
            model_name="baseinfo",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="baseinfo",
            name="short_address",
            field=models.TextField(
                blank=True,
                help_text="Для этикеток контрагентов",
                max_length=512,
                null=True,
                verbose_name="Короткий адрес",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbaseinfo",
            name="address",
            field=models.TextField(
                blank=True,
                help_text="Для этикеток товаров",
                max_length=512,
                null=True,
                verbose_name="Адрес",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbaseinfo",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="historicalbaseinfo",
            name="short_address",
            field=models.TextField(
                blank=True,
                help_text="Для этикеток контрагентов",
                max_length=512,
                null=True,
                verbose_name="Короткий адрес",
            ),
        ),
    ]
