# Generated by Django 5.2.8 on 2025-12-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_baseinfo_site_url_historicalbaseinfo_site_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduct",
            name="caption",
            field=models.TextField(
                default="Хранить при температуре от 0 до +6°С. Продукция может содержать аллергены: сельдерей, соя, арахис, орехи, рыба, морепродукты, пшеница.",
                verbose_name="Дополнительная информация",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="caption",
            field=models.TextField(
                default="Хранить при температуре от 0 до +6°С. Продукция может содержать аллергены: сельдерей, соя, арахис, орехи, рыба, морепродукты, пшеница.",
                verbose_name="Дополнительная информация",
            ),
        ),
    ]
