# Generated by Django 5.2.8 on 2025-12-16 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_historicalproduct_caption_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractorTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "этикетка контрагента",
                "verbose_name_plural": "этикетки контрагентов",
            },
        ),
        migrations.CreateModel(
            name="ProductTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "этикетка товара",
                "verbose_name_plural": "этикетки товаров",
            },
        ),
        migrations.RemoveConstraint(
            model_name="product",
            name="unique_barcode_per_template",
        ),
        migrations.AddField(
            model_name="contractortemplate",
            name="contractor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contractor_template",
                to="main.contractor",
                verbose_name="Контрагент",
            ),
        ),
        migrations.AddField(
            model_name="contractortemplate",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contractor_template",
                to="main.orgstandart",
                verbose_name="Шаблон",
            ),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_template",
                to="main.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_template",
                to="main.orgstandart",
                verbose_name="Шаблон",
            ),
        ),
    ]
