# Generated by Django 5.2.8 on 2025-12-16 13:07

from django.db import migrations

def forwards(apps, schema_editor):
    Product = apps.get_model("main", "Product")
    ProductTemplate = apps.get_model("main", "ProductTemplate")
    for p in Product.objects.all().iterator():
        if p.template_id:
            ProductTemplate.objects.create(product_id=p.pk, template_id=p.template_id)
    Contractor = apps.get_model("main", "Contractor")
    ContractorTemplate = apps.get_model("main", "ContractorTemplate")
    for c in Contractor.objects.all().iterator():
        if c.template_id:
            ContractorTemplate.objects.create(contractor_id=c.pk, template_id=c.template_id)

def backwards(apps, schema_editor):
    ProductTemplate = apps.get_model("main", "ProductTemplate")
    ProductTemplate.objects.all().delete()
    ContractorTemplate = apps.get_model("main", "ContractorTemplate")
    ContractorTemplate.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_contractortemplate_producttemplate_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
