# Generated by Django 5.2.8 on 2025-12-17 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_migrate_templates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contractor",
            name="template",
        ),
        migrations.RemoveField(
            model_name="historicalcontractor",
            name="template",
        ),
        migrations.RemoveField(
            model_name="historicalproduct",
            name="template",
        ),
        migrations.RemoveField(
            model_name="product",
            name="template",
        ),
        migrations.AlterField(
            model_name="contractortemplate",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contractor_template",
                to="main.template",
                verbose_name="Шаблон",
            ),
        ),
        migrations.AlterField(
            model_name="producttemplate",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_template",
                to="main.template",
                verbose_name="Шаблон",
            ),
        ),
    ]
