# Generated by Django 5.2.8 on 2025-12-18 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_remove_contractor_template_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractortemplate",
            options={
                "verbose_name": "этикетка контрагента (template)",
                "verbose_name_plural": "этикетки контрагентов (template)",
            },
        ),
        migrations.AlterModelOptions(
            name="producttemplate",
            options={
                "verbose_name": "этикетка товара (template)",
                "verbose_name_plural": "этикетки товаров (template)",
            },
        ),
    ]
