# Generated by Django 5.2.8 on 2025-12-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_contractortemplate_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="status",
            field=models.CharField(
                choices=[("CREATED", "Добавлен"), ("ARCHIEVED", "Архивирован")],
                default="CREATED",
                max_length=150,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("CREATED", "Добавлен"), ("ARCHIEVED", "Архивирован")],
                default="CREATED",
                max_length=150,
                verbose_name="Статус",
            ),
        ),
    ]
