# Generated by Django 5.2.8 on 2025-12-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_historicalproduct_status_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduct",
            name="status",
            field=models.CharField(
                choices=[("CREATED", "Доступен"), ("ARCHIEVED", "Архивирован")],
                default="CREATED",
                max_length=150,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("CREATED", "Доступен"), ("ARCHIEVED", "Архивирован")],
                default="CREATED",
                max_length=150,
                verbose_name="Статус",
            ),
        ),
    ]
