# Generated by Django 5.2.8 on 2026-01-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_historicalproduct_status_alter_product_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractorcategory",
            options={
                "verbose_name": "фирма-контрагент",
                "verbose_name_plural": "фирмы-контрагенты",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcontractorcategory",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical фирма-контрагент",
                "verbose_name_plural": "historical фирмы-контрагенты",
            },
        ),
    ]
