# Generated by Django 5.2.8 on 2026-03-16 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_contractorcategory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "ингредиент",
                "verbose_name_plural": "ингредиенты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight_grams", models.PositiveIntegerField(verbose_name="Вес, г")),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_ingredients",
                        to="main.ingredient",
                        verbose_name="Ингредиент",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_ingredients",
                        to="main.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "ингредиент товара",
                "verbose_name_plural": "ингредиенты товаров",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="ingredients_m2m",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                through="main.ProductIngredient",
                to="main.ingredient",
                verbose_name="Ингредиенты",
            ),
        ),
        migrations.AddConstraint(
            model_name="productingredient",
            constraint=models.UniqueConstraint(
                fields=("product", "ingredient"), name="uniq_product_ingredient"
            ),
        ),
    ]
