# Generated by Django 5.2.8 on 2026-03-16 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_ingredient_productingredient_product_ingredients_m2m_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Название")),
            ],
            options={
                "verbose_name": "цех",
                "verbose_name_plural": "цеха",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategoryWorkshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_workshops",
                        to="main.productcategory",
                        verbose_name="Категория товара",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workshop_categories",
                        to="main.workshop",
                        verbose_name="Цех",
                    ),
                ),
            ],
            options={
                "verbose_name": "цех категории товара",
                "verbose_name_plural": "цеха категорий товаров",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "workshop"), name="uniq_category_workshop"
                    )
                ],
            },
        ),
    ]
