# Generated by Django 5.2.8 on 2026-03-16 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_workshop_productcategoryworkshop"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="workshop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_categories",
                to="main.workshop",
                verbose_name="Цех",
            ),
        ),
        migrations.DeleteModel(
            name="ProductCategoryWorkshop",
        ),
    ]
