# Generated by Django 5.2.8 on 2026-03-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_productcategory_workshop_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproduct",
            name="best_before",
        ),
        migrations.RemoveField(
            model_name="product",
            name="best_before",
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="quantity",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Количество"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Количество"
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="calories",
            field=models.DecimalField(
                decimal_places=2,
                help_text="На 100 г продукта",
                max_digits=6,
                verbose_name="Калории",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="caption",
            field=models.TextField(
                blank=True,
                default="Хранить при температуре от 0 до +6°С. Продукция может содержать аллергены: сельдерей, соя, арахис, орехи, рыба, морепродукты, пшеница.",
                null=True,
                verbose_name="Дополнительная информация",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="carbs",
            field=models.DecimalField(
                decimal_places=2,
                help_text="На 100 г продукта",
                max_digits=6,
                verbose_name="Углеводы",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="fat",
            field=models.DecimalField(
                decimal_places=2,
                help_text="На 100 г продукта",
                max_digits=6,
                verbose_name="Жиры",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="ingredients",
            field=models.TextField(
                blank=True, max_length=1600, null=True, verbose_name="Состав"
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="protein",
            field=models.DecimalField(
                decimal_places=2,
                help_text="На 100 г продукта",
                max_digits=6,
                verbose_name="Белки",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="calories",
            field=models.DecimalField(
                decimal_places=2,
                help_text="На 100 г продукта",
                max_digits=6,
                verbose_name="Калории",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="caption",
            field=models.TextField(
                blank=True,
                default="Хранить при температуре от 0 до +6°С. Продукция может содержать аллергены: сельдерей, соя, арахис, орехи, рыба, морепродукты, пшеница.",
                null=True,
                verbose_name="Дополнительная информация",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="carbs",
            field=models.DecimalField(
                decimal_places=2,
                help_text="На 100 г продукта",
                max_digits=6,
                verbose_name="Углеводы",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="fat",
            field=models.DecimalField(
                decimal_places=2,
                help_text="На 100 г продукта",
                max_digits=6,
                verbose_name="Жиры",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="ingredients",
            field=models.TextField(
                blank=True, max_length=1600, null=True, verbose_name="Состав"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="protein",
            field=models.DecimalField(
                decimal_places=2,
                help_text="На 100 г продукта",
                max_digits=6,
                verbose_name="Белки",
            ),
        ),
    ]
