# Generated by Django 5.2.8 on 2026-03-17 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_remove_historicalproduct_best_before_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduct",
            name="barcode",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Штрихкод должен быть пустым или содержать ровно 13 цифр",
                        regex="^(\\d{13})?$",
                    )
                ],
                verbose_name="Штрихкод",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="calories",
            field=models.DecimalField(
                decimal_places=2,
                help_text="На 100 г. продукта",
                max_digits=6,
                verbose_name="Калории",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="carbs",
            field=models.DecimalField(
                decimal_places=2,
                help_text="На 100 г. продукта",
                max_digits=6,
                verbose_name="Углеводы",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="fat",
            field=models.DecimalField(
                decimal_places=2,
                help_text="На 100 г. продукта",
                max_digits=6,
                verbose_name="Жиры",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="protein",
            field=models.DecimalField(
                decimal_places=2,
                help_text="На 100 г. продукта",
                max_digits=6,
                verbose_name="Белки",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Штрихкод должен быть пустым или содержать ровно 13 цифр",
                        regex="^(\\d{13})?$",
                    )
                ],
                verbose_name="Штрихкод",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="calories",
            field=models.DecimalField(
                decimal_places=2,
                help_text="На 100 г. продукта",
                max_digits=6,
                verbose_name="Калории",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="carbs",
            field=models.DecimalField(
                decimal_places=2,
                help_text="На 100 г. продукта",
                max_digits=6,
                verbose_name="Углеводы",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="fat",
            field=models.DecimalField(
                decimal_places=2,
                help_text="На 100 г. продукта",
                max_digits=6,
                verbose_name="Жиры",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="protein",
            field=models.DecimalField(
                decimal_places=2,
                help_text="На 100 г. продукта",
                max_digits=6,
                verbose_name="Белки",
            ),
        ),
    ]
