# Generated by Django 5.2.8 on 2026-03-17 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_alter_historicalproduct_barcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Количество"),
        ),
    ]
