# Generated by Django 5.2.8 on 2026-03-17 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_alter_historicalproduct_price_alter_product_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductBestBefore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "days",
                    models.PositiveIntegerField(verbose_name="Срок годности, дней"),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Например: При температуре от 0 до +6°С",
                        verbose_name="Условия хранения",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="best_before_options",
                        to="main.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "срок годности товара",
                "verbose_name_plural": "сроки годности товара",
                "ordering": ["days"],
            },
        ),
    ]
