from reportlab.lib.enums import TA_LEFT, TA_CENTER
from reportlab.lib import colors

STYLES = {
    "contractor__title": {
        "fontName": "DejaVu Sans Bold",
        "fontSize": 18,
        "leading": 18,
        "alignment": TA_CENTER,
        "textColor": colors.black,
        "leftIndent": 3,
        "rightIndent": 3,
        "bold": True,
    },
    "contractor__subtitle_1": {
        "fontName": "DejaVu Sans Bold",
        "fontSize": 14,
        "leading": 14,
        "alignment": TA_CENTER,
        "textColor": colors.black,
        "leftIndent": 3,
        "rightIndent": 3,
        "bold": True,
    },
    "contractor__subtitle_2": {
        "fontName": "DejaVu Sans Bold",
        "fontSize": 10,
        "leading": 10,
        "alignment": TA_CENTER,
        "textColor": colors.black,
        "leftIndent": 3,
        "rightIndent": 3,
        "bold": True,
    },
    "contractor__caption": {
        "fontName": "DejaVu Sans Bold",
        "fontSize": 8,
        "leading": 10,
        "alignment": TA_CENTER,
        "textColor": colors.black,
        "leftIndent": 3,
        "rightIndent": 3,
        "bold": True,
    },
    "product__title": {
        "fontName": "DejaVu Sans Bold",
        "fontSize": 10,
        "leading": 10,
        "alignment": TA_CENTER,
        "textColor": colors.black,
        "leftIndent": 3,
        "rightIndent": 3,
        "bold": True,
    },
    "product__subtitle": {
        "fontName": "DejaVu Sans Bold",
        "fontSize": 4,
        "leading": 4,
        "alignment": TA_LEFT,
        "textColor": colors.black,
        "bold": True,
        "leftIndent": 3,
        "rightIndent": 3,
    },
    "product__body_1": {
        "fontName": "DejaVu Sans",
        "fontSize": 6,
        "leading": 6,
        "alignment": TA_LEFT,
        "textColor": colors.black,
        "spaceBefore": 0,
        "spaceAfter": 10,
        "leftIndent": 3,
        "rightIndent": 3,
    },
    "product__body_2": {
        "fontName": "DejaVu Sans",
        "fontSize": 4.5,
        "leading": 5,
        "alignment": TA_LEFT,
        "textColor": colors.black,
        "leftIndent": 3,
        "rightIndent": 0,
    },
    "product__caption": {
        "fontName": "DejaVu Sans",
        "fontSize": 4,
        "leading": 4.5,
        "alignment": TA_LEFT,
        "textColor": colors.black,
        "leftIndent": 3,
        "rightIndent": 0,
    },
}