# Generated by Django 5.2.8 on 2026-01-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractoruser",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Активен"), ("INACTIVE", "Не активен")],
                default="ACTIVE",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
    ]
