# Generated by Django 5.2.8 on 2026-01-10 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_contractorcategory_options_and_more"),
        ("orders", "0002_contractoruser_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ordersupply",
            options={
                "ordering": ["-date", "-created_at", "-updated_at"],
                "verbose_name": "заявка (общая)",
                "verbose_name_plural": "заявки (общие)",
            },
        ),
        migrations.RemoveField(
            model_name="historicalordersupply",
            name="assembled_at",
        ),
        migrations.RemoveField(
            model_name="ordersupply",
            name="assembled_at",
        ),
        migrations.AddField(
            model_name="historicalordersupply",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Отгружено"),
        ),
        migrations.AddField(
            model_name="ordersupply",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Отгружено"),
        ),
        migrations.AlterField(
            model_name="contractororder",
            name="contractor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contractor_orders",
                to="orders.contractoruser",
                verbose_name="Контрагент",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontractororder",
            name="contractor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="orders.contractoruser",
                verbose_name="Контрагент",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractoruser",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("contractor",),
                name="unique_active_contractor_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="ordersupply",
            constraint=models.UniqueConstraint(
                fields=("created_at",), name="unique_date"
            ),
        ),
    ]
