# Generated by Django 5.2.8 on 2026-01-10 10:40

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_ordersupply_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contractororder",
            name="unique_contractor_date",
        ),
        migrations.RenameField(
            model_name="contractororder",
            old_name="contractor",
            new_name="contractor_user",
        ),
        migrations.RenameField(
            model_name="historicalcontractororder",
            old_name="contractor",
            new_name="contractor_user",
        ),
        migrations.AlterField(
            model_name="contractororder",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Создан"),
                    ("PROCESSED", "Исполнен"),
                    ("CANCELLED", "Отменен"),
                ],
                default="CREATED",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontractororder",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Создан"),
                    ("PROCESSED", "Исполнен"),
                    ("CANCELLED", "Отменен"),
                ],
                default="CREATED",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="historicalordersupply",
            name="date",
            field=models.DateField(default="2026-01-10", verbose_name="Дата поставки"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ordersupply",
            name="date",
            field=models.DateField(default="2026-01-10", verbose_name="Дата поставки"),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="contractororder",
            constraint=models.UniqueConstraint(
                fields=("contractor_user", "date"), name="unique_contractor_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="ordersupply",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "date__gte",
                        django.db.models.functions.datetime.TruncDate(
                            django.db.models.functions.datetime.Now()
                        ),
                    )
                ),
                name="order_date_not_in_past",
            ),
        ),
    ]
