# Generated by Django 5.2.8 on 2026-03-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_contractororder_unique_contractor_date_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ordersupply",
            name="unique_date",
        ),
        migrations.AddConstraint(
            model_name="ordersupply",
            constraint=models.UniqueConstraint(fields=("date",), name="unique_date"),
        ),
    ]
