# Generated by Django 5.2.8 on 2026-03-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_ordersupply_unique_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalordersupply",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
        migrations.AddField(
            model_name="ordersupply",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
    ]
